version: "3.4"

x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  postgres:
    <<: *default

    container_name: postgres

    image: "postgres:latest"

    ports:
      - "7777:5432"

    env_file:
      - .env

    volumes:
      - ./postgres:/var/lib/postgresql/data

  homeassistant:
    <<: *default

    container_name: homeassistant

    image: "ghcr.io/home-assistant/home-assistant:stable"

    volumes:
      - /data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro

    # ports:
    # - "8123:8123"

    privileged: true
    network_mode: host
