version: "3.4"

x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  flame:
    <<: *default

    image: pawelmalak/flame

    container_name: flame

    volumes:
      - ./services/flame/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "5005:5005"

    env_file:
      - .env

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest

    container_name: jellyfin

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angelos

    volumes:
      - ./services/jellyfin/config:/config
      - ./services/jellyfin/tvshows:/data/tvshows
      - ./services/jellyfin/movies:/data/movies

    ports:
      - "8096:8096"
