version: "3.4"

x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  flame:
    <<: *default

    image: pawelmalak/flame

    container_name: flame

    volumes:
      - ./data/flame/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "5005:5005"

    env_file:
      - .env # Only contains PASSWORD.

  nextcloud:
    <<: *default

    image: nextcloud

    container_name: nextcloud

    ports:
      - "8080:80"

  jellyfin:
    <<: *default

    image: lscr.io/linuxserver/jellyfin:latest

    container_name: jellyfin

    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angelos"

    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/tvshows:/data/tvshows
      - ./data/jellyfin/movies:/data/movies

    ports:
      - "8096:8096"

  minecraft:
    <<: *default

    container_name: minecraft

    image: itzg/minecraft-server

    ports:
      - "25565:25565"
      - "8123:8123"

    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      SPIGET_RESOURCES: "274" # dynmap
      DIFFICULTY: "hard"
      MOTD: "Xithrius's Paper Minecraft Server powered by Docker"
      MODE: "survival"
      VIEW_DISTANCE: 16
      FORCE_GAMEMODE: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_RCON: "true"
      RCON_PORT: 25575 # Doesn't need to be set, just a reminder.
      # RCON_PASSWORD is set in .env
      RCON_CMDS_STARTUP: |-
        op Xithrius
        whitelist on
        whitelist add Xithrius
        whitelist reload
        scoreboard objectives add Deaths deathCount
        scoreboard objectives setdisplay belowName Deaths
        pregen start 200

    env_file:
      - .env

    tty: true

    stdin_open: true

    volumes:
      - ./data/minecraft:/data
