version: "3.4"

x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  flame:
    <<: *default

    image: pawelmalak/flame

    container_name: flame

    volumes:
      - ./data/flame/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "5005:5005"

    env_file:
      - .env # Only contains PASSWORD.

  postgres:
    <<: *default

    image: postgres

    container_name: postgres

    hostname: "nc-postgres"

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    env_file:
      - .env # POSTGRES_USER, POSTGRES_PASSWORD

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: "nextcloud_db"

  nextcloud:
    <<: *default

    image: nextcloud

    container_name: nextcloud

    ports:
      - "8080:80"

    env_file:
      - .env # POSTGRES_USER, POSTGRES_PASSWORD

    environment:
      POSTGRES_HOST: "nc-postgres"
      POSTGRES_DB: "nextcloud_db"

    depends_on:
      - postgres

  jellyfin:
    <<: *default

    image: lscr.io/linuxserver/jellyfin:latest

    container_name: jellyfin

    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angelos"

    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/tvshows:/data/tvshows
      - ./data/jellyfin/movies:/data/movies

    ports:
      - "8096:8096"
