version: "3.4"

x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  postgres:
    <<: *default

    image: postgres

    container_name: postgres

    hostname: "nc-postgres"

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    env_file:
      - .env # POSTGRES_USER, POSTGRES_PASSWORD

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: "nextcloud_db"

  nextcloud:
    <<: *default

    image: nextcloud

    container_name: nextcloud

    ports:
      - "8080:80"

    env_file:
      - .env # POSTGRES_USER, POSTGRES_PASSWORD

    environment:
      POSTGRES_HOST: "nc-postgres"
      POSTGRES_DB: "nextcloud_db"
      NEXTCLOUD_TRUSTED_DOMAINS: drive.xithrius.cloud

    depends_on:
      - postgres

  jellyfin:
    <<: *default

    image: jellyfin/jellyfin

    container_name: jellyfin

    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angelos"

    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/tvshows:/data/tvshows
      - ./data/jellyfin/movies:/data/movies

    ports:
      - "8096:8096"
