version: "3.4"

x-default: &default
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  homer:
    <<: *default

    image: b4bz/homer

    container_name: homer

    ports:
      - 8080:8080

    user:
      - 1000:1000

    environment:
      - INIT_ASSETS=1 # default

  # scrutiny:
  #   <<: *default

  #   container_name: scrutiny

  #   image: ghcr.io/analogj/scrutiny:master-omnibus

  #   cap_add:
  #     - SYS_RAWIO

  #   ports:
  #     - "8080:8080" # webapp
  #     - "8086:8086" # influxDB admin

  #   volumes:
  #     - /run/udev:/run/udev:ro
  #     - ./config:/opt/scrutiny/config
  #     - ./influxdb:/opt/scrutiny/influxdb

  #   devices:
  #     - "/dev/sda"
