version: "3.4"

x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  postgres:
    <<: *default

    container_name: postgres

    image: "postgres:latest"

    ports:
      - "7777:5432"

    volumes:
      - ./postgres:/var/lib/postgresql/data

  gitea:
    <<: *default

    image: "gitea/gitea:latest"

    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres:5432
      GITEA__database__NAME: site
      GITEA__database__USER: site
      GITEA__database__PASSWD: site

    volumes:
      - $PWD/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "3001:3001"
      - "222:22"

    depends_on:
      - postgres

  jellyfin:
    <<: *default

    image: jellyfin/jellyfin

    container_name: jellyfin

    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angelos"

    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/tvshows:/data/tvshows
      - ./data/jellyfin/movies:/data/movies

    ports:
      - "8096:8096"
