version: "3.4"

x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  postgres:
    <<: *default

    container_name: postgres

    image: "postgres:latest"

    ports:
      - "7777:5432"

    volumes:
      - ./postgres:/var/lib/postgresql/data

  jellyfin:
    <<: *default

    image: jellyfin/jellyfin

    container_name: jellyfin

    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angelos"

    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/tvshows:/data/tvshows
      - ./data/jellyfin/movies:/data/movies

    ports:
      - "8096:8096"
