version: "3.4"

x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  postgres:
    <<: *default

    container_name: postgres

    image: "postgres:latest"

    ports:
      - "7777:5432"

    env_file:
      - .env

    volumes:
      - ./postgres:/var/lib/postgresql/data

  jellyfin:
    <<: *default

    image: jellyfin/jellyfin

    container_name: jellyfin

    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angelos"

    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/tvshows:/data/tvshows
      - ./data/jellyfin/movies:/data/movies

    ports:
      - "8096:8096"

  minecraft:
    <<: *default

    container_name: minecraft

    image: itzg/minecraft-server

    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${RCON_PORT}:${RCON_PORT}

    environment:
      EULA: "true"
      TYPE: "PAPER"
      VERSION: "1.19.3"
      DIFFICULTY: "hard"
      MOTD: "Xithrius's Minecraft Server Powered by Docker."
      MODE: "survival"
      VIEW_DISTANCE: 16
      FORCE_GAMEMODE: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENFORCE_WHITELIST: "true"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: 0
      JVM_DD_OPTS: "-Paper.bypassHostCheck true -paper.useLegacyPluginLoading true"
      RCON_CMDS_STARTUP: |-
        op Xithrius
        whitelist on
        whitelist add Xithrius
        whitelist reload
        scoreboard objectives add Deaths deathCount
        scoreboard objectives setdisplay belowName Deaths

    env_file:
      - .env

    tty: true

    stdin_open: true

    volumes:
      - ./data/minecraft:/data
