version: "3.8"

x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  velocity:
    <<: *default

    container_name: velocity

    image: itzg/bungeecord

    env_file:
      - .env

    ports:
      - "25565:25577"

    environment:
      TYPE: "VELOCITY"
      DEBUG: "false"
      ENABLE_RCON: "false"
      CFG_MOTD: "Powered by Docker"

    volumes:
      - ./services/velocity/config.yml:/config/config.yml
      - ./services/velocity/velocity.toml:/config/velocity.toml
      - ./data/velocity/proxy:/server

  mc-modded:
    <<: *default

    image: itzg/minecraft-server

    container_name: mc-modded

    tty: true
    stdin_open: true

    env_file:
      - .env

    ports:
      - "25585:25585"

    environment:
      EULA: "true"
      ONLINE_MODE: "TRUE"
      SERVER_PORT: "25585"
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9
      CF_FILENAME_MATCHER: "0.2.10"
      CF_FORCE_SYNCHRONIZE: "true"
      CF_EXCLUDE_MODS: |
        embeddium
      MEMORY: 12G

    volumes:
      - ./data/mc-modded/data/:/data
      - ./data/mc-modded/downloads:/downloads

  mc:
    <<: *default

    image: itzg/minecraft-server

    container_name: mc

    tty: true
    stdin_open: true

    ports:
      - "25575:25575"

    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      SERVER_PORT: "25575"
      VERSION: "1.20.1"
      MEMORY: "12G"

    volumes:
      - ./data/mc/data/:/data

volumes:
  velocity: {}
  mc-modded: {}
  mc: {}
