version: "3.8"

x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  vanilla-mc:
    <<: *default

    image: itzg/minecraft-server

    container_name: vanilla-mc

    tty: true
    stdin_open: true

    ports:
      - "25567:25567"

    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      SERVER_PORT: "25567"
      VERSION: "1.20.1"
      MEMORY: "12G"

    volumes:
      - ./data/vanilla-mc/data/:/data

  modded-mc:
    <<: *default

    image: itzg/minecraft-server

    container_name: modded-mc

    tty: true
    stdin_open: true

    env_file:
      - .env

    ports:
      - "25568:25568"

    environment:
      EULA: "true"
      SERVER_PORT: "25568"
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9
      CF_FILENAME_MATCHER: "0.2.10"
      CF_FORCE_SYNCHRONIZE: "true"
      CF_EXCLUDE_MODS: |
        embeddium
      MEMORY: 12G

    volumes:
      - ./data/modded-mc/data/:/data
      - ./data/modded-mc/downloads:/downloads

  mc-router:
    <<: *default

    image: itzg/mc-router

    container_name: mc-router

    depends_on:
      - vanilla-mc
      - modded-mc

    environment:
      MAPPING: |
        vanilla-mc.xithrius.cloud=vanilla-mc:25567
        modded-mc.xithrius.cloud=modded-mc:25568

    ports:
      - "25565:25565"

  jellyfin:
    <<: *default

    container_name: jellyfin

    image: "jellyfin/jellyfin"

    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angelos"

    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/tvshows:/data/tvshows
      - ./data/jellyfin/movies:/data/movies
      - ./data/jellyfin/pictures:/data/pictures
      - ./data/jellyfin/memes-images:/data/memes-images
      - ./data/jellyfin/memes-videos:/data/memes-videos

    ports:
      - "8096:8096"
