x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  gitlab:
    <<: *default

    image: "docker.io/gitlab/gitlab-ce:17.1.1-ce.0"

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2224

    ports:
      - "0.0.0.0:8929:80"
      - "0.0.0.0:2224:22"

    volumes:
      - "$GITLAB_HOME/config:/etc/gitlab"
      - "$GITLAB_HOME/logs:/var/log/gitlab"
      - "$GITLAB_HOME/data:/var/opt/gitlab"

    shm_size: "256m"

    networks:
      - gitlab

networks:
  gitlab:
