x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy:
  restart: unless-stopped

services:
  grafana:
    <<: *logging

    image: "docker.io/grafana/grafana:11.4.0"

    user: "0"

    volumes:
    - ./data/grafana:/var/lib/grafana
    - ./config/grafana/provisioning:/etc/grafana/provisioning
    - ./config/grafana/dashboards:/var/lib/grafana/dashboards

    ports:
    - "127.0.0.1:3000:3000"

    networks:
    - infra-metrics
