x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  # vanilla-mc:
  #   <<: *default

  #   image: itzg/minecraft-server

  #   container_name: vanilla-mc

  #   tty: true
  #   stdin_open: true

  #   ports:
  #     - "127.0.0.1:25567:25567"

  #   env_file:
  #     - .env

  #   environment:
  #     EULA: "TRUE"
  #     TYPE: "FABRIC"
  #     SERVER_PORT: "25567"
  #     VERSION: "1.21.0"
  #     MEMORY: "12G"
  #     VIEW_DISTANCE: 16

  #   volumes:
  #     - ./data/minecraft/instances/vanilla-mc/data/:/data

  modded-mc:
    <<: *default

    container_name: modded-mc

    image: "itzg/minecraft-server"

    tty: true
    stdin_open: true

    env_file:
      - .env

    ports:
      - "127.0.0.1:25568:25568"

    environment:
      EULA: "true"
      SERVER_PORT: "25568"
      MOD_PLATFORM: "AUTO_CURSEFORGE"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-9"
      CF_FILENAME_MATCHER: "0.2.61"
      CF_FORCE_SYNCHRONIZE: "true"
      MEMORY: "12G"

    volumes:
      - ./data/minecraft/instances/modded-mc/data/:/data
      - ./data/minecraft/instances/modded-mc/downloads:/downloads

  mc-router:
    <<: *default

    image: itzg/mc-router

    container_name: mc-router

    depends_on:
      - modded-mc
      # - vanilla-mc

    environment:
      MAPPING: |
        modded-mc.xithrius.cloud=modded-mc:25568
      # vanilla-mc.xithrius.cloud=vanilla-mc:25567

    ports:
      - "127.0.0.1:25565:25565"
