x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  postgres:
    <<: *default

    container_name: postgres

    image: "postgres:latest"

    ports:
      - "127.0.0.1:7777:5432"

    env_file:
      - .env

    volumes:
      - ./postgres:/var/lib/postgresql/data

  jellyfin:
    <<: *default

    container_name: jellyfin

    image: "jellyfin/jellyfin"

    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angelos"

    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/tvshows:/data/tvshows
      - ./data/jellyfin/movies:/data/movies
      - ./data/jellyfin/pictures:/data/pictures
      - ./data/jellyfin/memes-images:/data/memes-images
      - ./data/jellyfin/memes-videos:/data/memes-videos

    ports:
      - "8096:8096"

  homeassistant:
    <<: *default

    container_name: homeassistant

    image: "ghcr.io/home-assistant/home-assistant:stable"

    volumes:
      - /data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro

    privileged: true
    network_mode: host
