x-default: &default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  netdata:
    <<: *default

    container_name: netdata

    image: "netdata/netdata"

    pid: host

    network_mode: host

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN

    security_opt:
      - apparmor:unconfined

    volumes:
      - ./data/netdata/config:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus:/run/dbus:r

    ports:
      - "127.0.0.1:19999:19999"

volumes:
  netdatalib:
  netdatacache:
